/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package org.by.typer.gui;

import java.awt.event.KeyEvent;
import java.awt.event.MouseEvent;
import javax.swing.ToolTipManager;
import org.by.typer.TypeEvent;
import org.by.typer.Typer;
import org.by.typer.Utils;

/**
 *
 * @author owner
 */
public class EventFrame extends javax.swing.JFrame {

    /**
     * Creates new form EventFrame
     */
    public EventFrame() {
        this("", 0, 0, -1, true);
    }
    
    private int pos;
    public EventFrame(String text, int key, int mask, int pos, boolean active) {
        initComponents();
        loadComboBox();
        setVisible(true);
        setSize(271, 320);
        this.pos = pos;
        if (pos == -1) {
            setTitle("New Item");
        } else {
            setTitle("Edit Item");
        }
        
        jTextField1.setText(text);
        selectKey(key);
        if ((mask & Utils.MODIFIER_KEYS.SHIFT.getMask()) != 0)
            jCheckBox1.setSelected(true);
        if ((mask & Utils.MODIFIER_KEYS.CTRL.getMask()) != 0)
            jCheckBox2.setSelected(true);
        if ((mask & Utils.MODIFIER_KEYS.META.getMask()) != 0)
            jCheckBox3.setSelected(true);
        if ((mask & Utils.MODIFIER_KEYS.ALT.getMask()) != 0)
            jCheckBox4.setSelected(true);
        jCheckBox5.setSelected(active);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jCheckBox5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setText("Text to type");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 10, 110, 18);

        jTextField1.setToolTipText("Please enter text to be typed");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(10, 30, 250, 28);
        getContentPane().add(jSeparator1);
        jSeparator1.setBounds(10, 60, 250, 10);

        jLabel2.setText("Hotkey");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 70, 110, 18);

        jComboBox1.setEditor(null);
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(10, 90, 120, 28);

        jCheckBox1.setText("Shift");
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(10, 120, 120, 24);

        jCheckBox2.setText("Ctrl");
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(10, 150, 120, 24);

        jCheckBox3.setText("Meta");
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(150, 120, 110, 24);

        jCheckBox4.setText("Alt");
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(150, 150, 110, 24);

        jButton1.setText("Accept");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(10, 250, 120, 30);

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(140, 250, 120, 30);
        getContentPane().add(jSeparator2);
        jSeparator2.setBounds(10, 180, 250, 10);

        jCheckBox5.setSelected(true);
        jCheckBox5.setText("Active");
        getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(10, 190, 250, 24);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        
        selectKey(evt.getKeyCode());
        evt.consume();
    }//GEN-LAST:event_jComboBox1KeyPressed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (jTextField1.getText().length() == 0) {
            ToolTipManager.sharedInstance().mouseMoved(new MouseEvent(jTextField1,
            0, 0, 0, 0, 0, 0, false));
            return;
        }
        
        String text = jTextField1.getText();
        int key = Utils.getKeyForName(jComboBox1.getSelectedItem().toString());
        int mask = 0;
        if (jCheckBox1.isSelected())
            mask |= Utils.MODIFIER_KEYS.SHIFT.getMask();
        if (jCheckBox2.isSelected())
            mask |= Utils.MODIFIER_KEYS.CTRL.getMask();
        if (jCheckBox3.isSelected())
            mask |= Utils.MODIFIER_KEYS.META.getMask();
        if (jCheckBox4.isSelected())
            mask |= Utils.MODIFIER_KEYS.ALT.getMask();
        boolean active = jCheckBox5.isSelected();
        
        if (pos >= 0) {
            TypeEvent t = Typer.getEvents().get(pos);
            t.setText(text);
            t.setHotkey(key);
            t.setMask(mask);
            t.setActive(active);
        } else {
            TypeEvent t = new TypeEvent(text, key, mask, active);
            Typer.getEvents().add(t);
        }
        Typer.getUI().loadEvents();
        Typer.saveToFile();
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    
    private void loadComboBox() {
        for (String a : Utils.TOP_LEVEL_KEYS)
            jComboBox1.addItem(a);
    }
    
    private void selectKey(int a) {
        for (int i = 0; i < jComboBox1.getItemCount(); i++) {
            if (jComboBox1.getItemAt(i).equals(KeyEvent.getKeyText(a))) {
                jComboBox1.setSelectedIndex(i);
                jComboBox1.setPopupVisible(false);
                break;
            }
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
